# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6697172a81ce7eaf787c4ef5d2912d6ef521bcae1ad2041acf4f0d44cd8c3300a826b80df294013997d54869dcc6562b44f136c806ec76e2160b89eb9ab3fed9

test:
  secret_key_base: 7fb2967d746a766a7ce2b1b99a6fe56a2fc08d2f0f1233c3afd3923a4365b164cf8735fc9519238d39d8830c4f1ceccd29255238e7fcc365d6a6c05a2aa5f7b5

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
